name: wavenet-animation
dependencies:
    - conda-forge::funcsigs=1.0.2=py27_0
    - conda-forge::mock=2.0.0=py27_0
    - conda-forge::pbr=1.10.0=py27_0
    - conda-forge::protobuf=3.1.0=py27_0
    - conda-forge::six=1.10.0=py27_1
    - conda-forge::tensorflow=0.12.1=py27_1
    - mkl=2017.0.1=0
    - numpy=1.12.0=py27_0
    - openssl=1.0.2k=0
    - pip=9.0.1=py27_1
    - python=2.7.13=0
    - readline=6.2=2
    - setuptools=27.2.0=py27_0
    - sqlite=3.13.0=0
    - tk=8.5.18=0
    - wheel=0.29.0=py27_0
    - zlib=1.2.8=3
